### ISSUE TITLE
[EMPTY REPOSITORY]

### ISSUE THREAD

**Issue by ritwickbhargav80** [shivaniaakanksha/hacktoberfest-fest2020#1]
At least add some files to contribute.

**Comment by shivaniaakanksha** [comment]
I changed my mind, now contributing to dsckiet repository @ritwickbhargav80 sir.

**Comment by ritwickbhargav80** [comment]
Pull Requests will only count toward earning a T-shirt or planting a tree if they are labeled as <b>'hacktoberfest-accepted'</b> by a maintainer, or submitted in a repository classified.

**Comment by shivaniaakanksha** [comment]
> Pull Requests will only count toward earning a T-shirt or planting a tree if they are labeled as 'hacktoberfest-accepted' by a maintainer, or submitted in a repository classified.

okay, I will take care of this. Thank you very much
